export const items = [
  {
    id: 1,
    name: "Running Shoes",
    image: "/images/running_shoes.avif",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam unde deserunt voluptatum.",
    price: 99,
    category: "clothing",
  },
  {
    id: 2,
    name: "Formal Shoes",
    image: "/images/formal_shoes.avif",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam unde deserunt voluptatum.",
    price: 99,
    category: "clothing",
  },
  {
    id: 3,
    name: "Casual Shoes",
    image: "/images/casual_shoes.avif",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam unde deserunt voluptatum.",
    price: 99,
    category: "clothing",
  },
  {
    id: 4,
    name: "Camera",
    image: "/images/camera.avif",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam unde deserunt voluptatum.",
    price: 99,
    category: "electronics",
  },
  {
    id: 5,
    name: "Earbud",
    image: "/images/earpods.avif",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam unde deserunt voluptatum.",
    price: 99,
    category: "electronics",
  },
  {
    id: 6,
    name: "Headphone",
    image: "/images/headphone.avif",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam unde deserunt voluptatum.",
    price: 99,
    category: "electronics",
  },
  {
    id: 7,
    name: "Sofa",
    image: "/images/sofa.avif",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam unde deserunt voluptatum.",
    price: 99,
    category: "home",
  },
  {
    id: 8,
    name: "Chair",
    image: "/images/chair.avif",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam unde deserunt voluptatum.",
    price: 99,
    category: "home",
  },
  {
    id: 9,
    name: "Study Lamp",
    image: "/images/lamp.avif",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam unde deserunt voluptatum.",
    price: 99,
    category: "home", // Added missing category
  },
  {
    id: 10,
    name: "Shirt",
    image: "/images/running_shoes.avif", // You might want to fix this if wrong
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam unde deserunt voluptatum.",
    price: 99,
    category: "clothing",
  },
  {
    id: 11,
    name: "T-Shirt",
    image: "/images/tshirt.avif",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam unde deserunt voluptatum.",
    price: 99,
    category: "clothing",
  },
];
